/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/menu/{menu_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMenuById"];
        put: operations["updateMenu"];
        post?: never;
        delete: operations["deleteMenu"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** email로 주문 조회 */
        get: operations["getOrdersByEmail"];
        put?: never;
        /** 주문 생성 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllMenus"];
        put?: never;
        post: operations["addMenu"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order-menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Empty: Record<string, never>;
        RsDataEmpty: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["Empty"];
        };
        Menu: {
            /** Format: int64 */
            id?: number;
            name?: string;
            type?: string;
            /** Format: int32 */
            price?: number;
        };
        MenuDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            type?: string;
            /** Format: int32 */
            price?: number;
        };
        RsDataMenuDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["MenuDto"];
        };
        OrderReqBody: {
            email?: string;
            address: string;
            /** Format: int32 */
            postalCode: number;
            orders: {
                [key: string]: number;
            };
        };
        OrderDto: {
            /** Format: int64 */
            id?: number;
            email?: string;
            address?: string;
            /** Format: int32 */
            postalCode?: number;
            orders?: {
                [key: string]: number;
            };
        };
        RsDataOrderDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["OrderDto"];
        };
        MenuDataDto: {
            /** Format: int64 */
            menuId?: number;
            menuName?: string;
            /** Format: int32 */
            menuPrice?: number;
            /** Format: int32 */
            menuCount?: number;
        };
        OrderMenuWithOrderDto: {
            /** Format: int64 */
            orderId?: number;
            email?: string;
            address?: string;
            /** Format: int32 */
            postalCode?: number;
            menuData?: components["schemas"]["MenuDataDto"][];
            /** Format: date-time */
            orderTime?: string;
            /** Format: int32 */
            totalPrice?: number;
            after2pm?: boolean;
        };
        OrderMenuDto: {
            /** Format: int64 */
            orderId?: number;
            menuData?: components["schemas"]["MenuDataDto"][];
            /** Format: date-time */
            orderTime?: string;
            /** Format: int32 */
            totalPrice?: number;
            after2pm?: boolean;
        };
        RsDataListOrderMenuDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["OrderMenuDto"][];
        };
        RsDataListMenuDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["MenuDto"][];
        };
        RsDataVoid: {
            resultCode: string;
            msg: string;
            data: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMenuById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Menu"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    updateMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Menu"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMenuDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    deleteMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    getOrdersByEmail: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderMenuWithOrderDto"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataOrderDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    getAllMenus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListMenuDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    addMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataMenuDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    getAllOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListOrderMenuDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
}
