spring:
  application:
    name: coffee
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  springdoc:
    default-produces-media-type: application/json;charset=UTF-8
  logging:
    level:
      springframework:
        security: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE
  custom:
    jwt:
      secretKey: abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789
    accessToken:
      expirationSeconds: "#{60*20}"